From: Ansgar Burchardt <ansgar@43-1.org>
Date: Sun, 21 Jun 2009 19:41:17 +0200
Subject: Install man page with correct section in filename
--- libnet-mac-vendor-perl.orig/Makefile.PL
+++ libnet-mac-vendor-perl/Makefile.PL
@@ -20,7 +20,7 @@
 		},
 
 	'MAN3PODS'     => {
-		'lib/Vendor.pm' => '$(INST_MAN3DIR)/Net::MAC::Vendor.3',
+		'lib/Vendor.pm' => '$(INST_MAN3DIR)/Net::MAC::Vendor.3pm',
 		},
 
 	clean  => { FILES    => q|Net-MAC-Vendor-* Makefile.old MANIFEST.bak| },
