#!/bin/sh
# Preinstallation script for libtest-harness-perl
# 
# Diverts perl's /usr/bin/prove (which comes from an earlier 
# version of libtest-harness-perl)

set -e

if [ "$1" = install ] || [ "$1" = upgrade ]
    then
    dpkg-divert --package libtest-harness-perl --add --rename \
	--divert /usr/bin/prove.diverted /usr/bin/prove
fi

#DEBHELPER#
